import type { PublicSection } from "./cms-types";

// Stub payload for TASK-002. Mirrors the shape of the real API response.
// TASK-003 replaces this with a build-time call to getLandingPage().
// All copy is DTM-specific and public-safe (capability-level only).
// See .agents/context/company-profile.md for the "Do not expose" list.

export const STUB_SECTIONS: PublicSection[] = [
  {
    sectionKey: "HERO",
    title: "Industrial parts procurement, end to end.",
    subtitle:
      "We source industrial parts from international manufacturers and deliver them to clients across Indonesia.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: "Contact our team",
    ctaLink: "/contact",
    sortOrder: 1,
    items: [],
  },
  {
    sectionKey: "ABOUT",
    title: "Who we are",
    subtitle: "Procurement and operations, on your side.",
    body:
      "Duta Teknologi Mandiri is an Indonesia-based procurement and operations company. We help clients source industrial parts from international suppliers, manage the full chain from purchase order to local fulfillment, and keep stock visible in real time.",
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 2,
    items: [],
  },
  {
    sectionKey: "SERVICES",
    title: "What we do",
    subtitle: "Capability areas we offer to clients.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 3,
    items: [
      { type: "SERVICE", title: "International sourcing", description: "We work with suppliers across multiple countries and currencies to find the right parts for your operation.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 1 },
      { type: "SERVICE", title: "Multi-currency purchasing", description: "Exchange rates, VAT, fees, and shipping costs are managed in one system so you see a single landed cost.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 2 },
      { type: "SERVICE", title: "Logistics coordination", description: "We coordinate with international and local shippers for the full freight journey.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 3 },
      { type: "SERVICE", title: "Real-time stock visibility", description: "Clients see current stock levels before they order, with full audit history on every movement.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 4 },
      { type: "SERVICE", title: "Order tracking", description: "Every order has a clear status from advance payment through delivery to fulfillment.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 5 },
      { type: "SERVICE", title: "Audit trail", description: "Every financial and status change is logged so you have a single source of truth.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 6 },
    ],
  },
  {
    sectionKey: "WHY_US",
    title: "Why teams work with us",
    subtitle: "Outcomes our clients see.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 4,
    items: [
      { type: "SERVICE", title: "Faster procurement", description: "A centralized workflow replaces scattered spreadsheets.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 1 },
      { type: "SERVICE", title: "Accurate landed cost", description: "Currency, VAT, fees, and shipping are calculated once, not by hand.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 2 },
      { type: "SERVICE", title: "Margin transparency", description: "Sell prices are derived from real cost data plus a published markup tier.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 3 },
      { type: "SERVICE", title: "Stock that matches reality", description: "Stock reflects the current import and sell state, not a stale snapshot.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 4 },
    ],
  },
  {
    sectionKey: "PROCESS",
    title: "How an order moves",
    subtitle: "From supplier to fulfillment.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 5,
    items: [
      { type: "SERVICE", title: "Supplier onboarding", description: "International suppliers are onboarded with country, contact, and currency details.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 1 },
      { type: "SERVICE", title: "Part catalog", description: "Every part is tracked by part number with full description and history.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 2 },
      { type: "SERVICE", title: "Procurement", description: "Each order records vendor, shipper, currency, exchange rate, VAT, fee, quantity, and shipping.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 3 },
      { type: "SERVICE", title: "Payment tracking", description: "Advance, partial, and final payments are tracked per order.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 4 },
      { type: "SERVICE", title: "Delivery", description: "When the import is delivered, stock increments and the order is fulfilled.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 5 },
    ],
  },
  {
    sectionKey: "STATS",
    title: "By the numbers",
    subtitle: JSON.stringify([
      { label: "Capabilities offered", value: "6" },
      { label: "Order stages tracked", value: "5" },
      { label: "Currency pairs supported", value: "Multi" },
      { label: "Audit entries per order", value: "100%" },
    ]),
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 6,
    items: [],
  },
  {
    sectionKey: "TESTIMONIALS",
    title: "What clients tell us",
    subtitle: "Voices from the field.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 7,
    items: [],
  },
  {
    sectionKey: "CLIENTS",
    title: "Industries we serve",
    subtitle: "From heavy industry to small workshops.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 8,
    items: [],
  },
  {
    sectionKey: "PARTNERS",
    title: "Logistics partners",
    subtitle: "International and domestic freight.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 9,
    items: [],
  },
  {
    sectionKey: "IMAGE_GALLERY",
    title: "From the operations floor",
    subtitle: null,
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 10,
    items: [],
  },
  {
    sectionKey: "FAQ",
    title: "Frequently asked",
    subtitle: null,
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 11,
    items: [
      { type: "FAQ", title: "How do you source parts?", description: "We work with international suppliers across multiple countries and currencies, and we manage the full chain from purchase order to local fulfillment.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 1 },
      { type: "FAQ", title: "Can you handle multiple currencies?", description: "Yes. Exchange rates, VAT, fees, and shipping costs are managed in one system so the landed cost is calculated once and is consistent across the order.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 2 },
      { type: "FAQ", title: "How is stock tracked?", description: "Every import that reaches delivered status increments central stock. Every fulfilled sell decrements it. Clients see current stock levels before they order.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 3 },
      { type: "FAQ", title: "Do you offer a single source of audit history?", description: "Yes. Every financial and status change is logged so you can trace any order from initial quote to fulfillment.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 4 },
    ],
  },
  {
    sectionKey: "CTA_BANNER",
    title: "Ready to source parts with a real partner?",
    subtitle: "Tell us what you need and we will get back within one business day.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: "Contact our team",
    ctaLink: "/contact",
    sortOrder: 12,
    items: [],
  },
];
