import type { PublicSection } from "./cms-types";

// Stub payload for TASK-002. Mirrors the shape of the real API response.
// TASK-003 replaces this with a build-time call to getLandingPage().
// All copy is DTM-specific and public-safe (sell-side framing only).
// See .agents/context/company-profile.md for the "Do not expose" list.

export const STUB_SECTIONS: PublicSection[] = [
  {
    sectionKey: "HERO",
    title: "Industrial parts, sourced and delivered.",
    subtitle:
      "We supply the industrial parts your operation needs, with full order tracking and real-time stock visibility.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: "Talk to our team",
    ctaLink: "/contact",
    sortOrder: 1,
    items: [],
  },
  {
    sectionKey: "ABOUT",
    title: "Who we are",
    subtitle: "A supplier you can plan around.",
    body:
      "Duta Teknologi Mandiri is an Indonesia-based supplier of industrial parts. We help buyers source the parts their operations need, track every order from confirmation to delivery, and keep stock visible in real time.",
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 2,
    items: [],
  },
  {
    sectionKey: "SERVICES",
    title: "What you get when you order from us",
    subtitle: "Capabilities that make procurement predictable.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 3,
    items: [
      { type: "SERVICE", title: "Industrial parts supply", description: "We supply the parts your operation needs, sourced from international manufacturers.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 1 },
      { type: "SERVICE", title: "Multi-currency purchasing", description: "Exchange rates, VAT, fees, and shipping costs are managed in one system so you see a single landed cost.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 2 },
      { type: "SERVICE", title: "Logistics coordination", description: "We coordinate freight from the supplier to your door, with clear status at every step.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 3 },
      { type: "SERVICE", title: "Real-time stock visibility", description: "You see current stock levels before you order, with full history on every movement.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 4 },
      { type: "SERVICE", title: "Order tracking", description: "Every order has a clear status from confirmation through delivery to fulfillment.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 5 },
      { type: "SERVICE", title: "Audit trail", description: "Every status change is logged so you have a single source of truth for the order.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 6 },
    ],
  },
  {
    sectionKey: "WHY_US",
    title: "Why buyers work with us",
    subtitle: "Outcomes our clients see.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 4,
    items: [
      { type: "SERVICE", title: "Faster parts procurement", description: "A centralized workflow replaces scattered spreadsheets.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 1 },
      { type: "SERVICE", title: "Accurate landed cost", description: "Currency, VAT, fees, and shipping are calculated once, not by hand.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 2 },
      { type: "SERVICE", title: "Margin transparency", description: "Sell prices are derived from real cost data plus a published markup tier.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 3 },
      { type: "SERVICE", title: "Stock that matches reality", description: "Stock reflects the current supply state, not a stale snapshot.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 4 },
    ],
  },
  {
    sectionKey: "PROCESS",
    title: "How an order moves",
    subtitle: "From your inquiry to delivery.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 5,
    items: [
      { type: "SERVICE", title: "Inquiry", description: "Tell us the part numbers and quantities you need. We confirm availability and lead time.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 1 },
      { type: "SERVICE", title: "Quotation", description: "We send a single, clear quotation with the landed cost and expected delivery window.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 2 },
      { type: "SERVICE", title: "Order confirmation", description: "Once confirmed, the order is locked in with a clear status you can check any time.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 3 },
      { type: "SERVICE", title: "Fulfillment", description: "We coordinate freight and keep you posted as the order moves toward delivery.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 4 },
      { type: "SERVICE", title: "Delivery", description: "The order arrives with documentation and a complete audit trail.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 5 },
    ],
  },
  {
    sectionKey: "STATS",
    title: "By the numbers",
    subtitle: JSON.stringify([
      { label: "Capabilities offered", value: "6" },
      { label: "Order stages tracked", value: "5" },
      { label: "Currency pairs supported", value: "Multi" },
      { label: "Audit entries per order", value: "100%" },
    ]),
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 6,
    items: [],
  },
  {
    sectionKey: "TESTIMONIALS",
    title: "What clients tell us",
    subtitle: "Voices from the field.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 7,
    items: [],
  },
  {
    sectionKey: "CLIENTS",
    title: "Industries we serve",
    subtitle: "From heavy industry to small workshops.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 8,
    items: [],
  },
  {
    sectionKey: "PARTNERS",
    title: "Logistics partners",
    subtitle: "International and domestic freight.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 9,
    items: [],
  },
  {
    sectionKey: "IMAGE_GALLERY",
    title: "From the operations floor",
    subtitle: null,
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 10,
    items: [],
  },
  {
    sectionKey: "FAQ",
    title: "Frequently asked",
    subtitle: null,
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: null,
    ctaLink: null,
    sortOrder: 11,
    items: [
      { type: "FAQ", title: "What do you supply?", description: "We supply industrial parts sourced from international manufacturers. Tell us what you need and we will confirm availability and lead time.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 1 },
      { type: "FAQ", title: "Can you handle multi-currency orders?", description: "Yes. Exchange rates, VAT, fees, and shipping costs are managed in one system so the landed cost is calculated once and is consistent across the order.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 2 },
      { type: "FAQ", title: "How do I see current stock?", description: "Stock levels are visible before you order, with full history on every movement so you can plan around the actual supply.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 3 },
      { type: "FAQ", title: "How is each order tracked?", description: "Every order has a clear status from confirmation through delivery to fulfillment, and every status change is logged.", imageUrl: null, imageAlt: null, authorName: null, authorTitle: null, authorCompany: null, sortOrder: 4 },
    ],
  },
  {
    sectionKey: "CTA_BANNER",
    title: "Need industrial parts you can plan around?",
    subtitle: "Tell us what you need and we will get back within one business day.",
    body: null,
    imageUrl: null,
    imageAlt: null,
    ctaText: "Talk to our team",
    ctaLink: "/contact",
    sortOrder: 12,
    items: [],
  },
];
